spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qxfly_blog?serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: prod
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml,classpath:mappers/admin/*.xml

qxfly:
  jwt:
    ignore:
      urls:
        - /favicon.ico  #网站图标
        - /gs  #获取公匙
        - /login   #登陆
        - /logout   #退出
        - /register   #注册
        - /updateLoginStatue   #检测更用户信息
        - /index/listSite   #网站列表
        - /index/listIndexNav   #首页导航
        - /download/**   # 下载
        - /v3/**   #api文档
        - /swagger-ui/**  #api文档
        - /doc.html/**
        - /webjars/**
        - /userAvatar/**   #用户头像
        - /userBgImg/**   #用户背景图片
        - /user/getUserInfo   #获取用户信息
        - /user/getSuggestAuthor  # 获取推荐作者
        - /user/findPassword  # 找回密码
        - /user/sendCode  # 找回密码
        - /article/listArticles   #文章列表
        - /article/getArticleById   #文章详情
        - /articleCover/**   #文章封面
        - /articleImage/**   #文章内容图片
        - /article/getArticleComments   #获取文章评论
        - /article/addArticleView   # 增加浏览量
        - /article/getTags   # 获取标签
        - /article/getClassifies   # 获取分类
        - /article/getArticleAttachment   #文章附件
        - /articleAttachment/**   #附件下载
        - /article/getCollectionArticles   #获取用户收藏
        - /index/listLeaveMessage   #列出留言
        - /index/sendLeaveMessage   #发送留言
        - /index/deleteLeaveMessage  #删除留言
        - /index/getSiteStatus  #获取站点状态
        



