spring:
  datasource:
    username: root
    password: Zjky@601899
  application:
    name: zjky
logging:
  level:
    root: info
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
qxfly:
  domain: http://10.61.4.160/fly
  file:
    uploadPath: /qxfly/web/data/upload/
    path:
      VirtualPath: file:///www/qxfly/data/upload/
      userImg: ${qxfly.domain}/userAvatar/
      userBgImg: ${qxfly.domain}/userBgImg/
      articleCover: ${qxfly.domain}/articleCover/
      articleImage: ${qxfly.domain}/articleImage/
      articleAttachment: ${qxfly.domain}/articleAttachment/
      systemBgImg: ${qxfly.domain}/systemBgImg/
      warehousePicture: ${qxfly.domain}/warehousePicture/
      purchasePicture: ${qxfly.domain}/purchasePicture/