spring:
  datasource:
    username: root
    password: FLY334955ffh.
  application:
    name: qxfly-prod
logging:
  level:
    root: info
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
qxfly:
  domain: https://qxfly.xyz/fly
  file:
    uploadPath: /qxfly/web/data/upload/
    path:
      VirtualPath: file:///www/qxfly/data/upload/
      userImg: ${qxfly.domain}/userAvatar/
      userBgImg: ${qxfly.domain}/userBgImg/
      articleCover: ${qxfly.domain}/articleCover/
      articleImage: ${qxfly.domain}/articleImage/
      articleAttachment: ${qxfly.domain}/articleAttachment/
      systemBgImg: ${qxfly.domain}/systemBgImg/
